# Generated by Django 4.2 on 2024-11-09 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
